import type { WorkRequest } from "./types"

export const FACILITIES = [
  "Anlaggning A - Reaktor 1",
  "Anlaggning B - Turbin 2",
  "Anlaggning C - Kylsystem",
  "Anlaggning D - Elforsorjning",
]

export const MOCK_REQUESTS: WorkRequest[] = [
  {
    id: "ARB-1001",
    title: "Arbetsbegäran 1",
    description:
      "Ventil V-4021 visar tecken pa lackage och behover bytas. Arbetet kraver dranering av delkrets och installning av temporar bypass.",
    facility: "Anlaggning C - Kylsystem",
    object: "V-4021",
    requestedStart: "2026-02-20",
    duration: "8 timmar",
    riskImpact: "Medel - Kylkapacitet reducerad under arbetet. Backup-krets tillganglig.",
    status: "review",
    priority: "high",
    createdBy: "Anna Lindqvist",
    createdByRole: "applicant",
    createdAt: "2026-02-10T08:30:00",
    updatedAt: "2026-02-14T14:22:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
      { id: "r3", label: "Reservdelar bestallda", fulfilled: true },
      { id: "r4", label: "Sakerhetsgenomgang genomford", fulfilled: false, note: "Ej bokad annu" },
      { id: "r5", label: "Berorda system identifierade", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-10T08:30:00", actor: "Anna Lindqvist", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-10T09:00:00", actor: "Anna Lindqvist", role: "applicant", action: "Skickade in for granskning" },
      { id: "a3", timestamp: "2026-02-12T10:15:00", actor: "Erik Johansson", role: "shiftlead1", action: "Tilldelade sig arendet" },
      { id: "a4", timestamp: "2026-02-14T14:22:00", actor: "Erik Johansson", role: "shiftlead1", action: "Paborjade granskning", comment: "Ser bra ut, vanter pa sakerhetsgenomgang." },
    ],
    attachments: [
      { id: "att1", name: "Riskanalys_V4021.pdf", type: "pdf", size: "2.4 MB", uploadedBy: "Anna Lindqvist", uploadedAt: "2026-02-10T08:35:00", version: 1 },
      { id: "att2", name: "Ritning_Kylkrets2.dwg", type: "dwg", size: "15.8 MB", uploadedBy: "Anna Lindqvist", uploadedAt: "2026-02-10T08:40:00", version: 1 },
    ],
    documents: [
      { id: "doc1", name: "ARB.BEG #1001", version: 1, generatedBy: "System", generatedAt: "2026-02-10T09:00:00", format: "pdf" },
    ],
    approvers: [
      { role: "shiftlead1", name: "Erik Johansson" },
      { role: "shiftlead2", name: "Maria Svensson" },
    ],
  },
  {
    id: "ARB-1002",
    title: "Inspektion av turbinlager T2-L3",
    description:
      "Planerad inspektion av turbinlager T2-L3 efter vibrationsindikering. Inga driftavbrott kravs om utford under planerat stopp.",
    facility: "Anlaggning B - Turbin 2",
    object: "T2-L3",
    requestedStart: "2026-02-25",
    duration: "4 timmar",
    riskImpact: "Lag - Utfors under planerat underhallsstopp.",
    status: "approved",
    priority: "medium",
    createdBy: "Karin Bergstrom",
    createdByRole: "applicant",
    createdAt: "2026-02-08T11:00:00",
    updatedAt: "2026-02-13T16:45:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
      { id: "r3", label: "Reservdelar bestallda", fulfilled: true },
      { id: "r4", label: "Sakerhetsgenomgang genomford", fulfilled: true },
      { id: "r5", label: "Berorda system identifierade", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-08T11:00:00", actor: "Karin Bergstrom", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-08T11:30:00", actor: "Karin Bergstrom", role: "applicant", action: "Skickade in for granskning" },
      { id: "a3", timestamp: "2026-02-10T09:00:00", actor: "Erik Johansson", role: "shiftlead1", action: "Godkande arbetsbegaran" },
      { id: "a4", timestamp: "2026-02-13T16:45:00", actor: "Maria Svensson", role: "shiftlead2", action: "Godkande arbetsbegaran" },
    ],
    attachments: [
      { id: "att1", name: "Vibrationsrapport_T2L3.pdf", type: "pdf", size: "1.1 MB", uploadedBy: "Karin Bergstrom", uploadedAt: "2026-02-08T11:10:00", version: 1 },
    ],
    documents: [
      { id: "doc1", name: "ARB.BEG #1002", version: 1, generatedBy: "System", generatedAt: "2026-02-08T11:30:00", format: "pdf" },
      { id: "doc2", name: "ARB.BEG #1002", version: 2, generatedBy: "System", generatedAt: "2026-02-13T16:50:00", format: "pdf" },
    ],
    approvers: [
      { role: "shiftlead1", name: "Erik Johansson", approved: true, date: "2026-02-10" },
      { role: "shiftlead2", name: "Maria Svensson", approved: true, date: "2026-02-13" },
    ],
  },
  {
    id: "ARB-1003",
    title: "Uppgradering styrskap reaktor 1",
    description:
      "Byte av PLC-modul i styrskap R1-SC-04. Kraver nedstangning av delsystem och noggrant igangkorningsforfarande.",
    facility: "Anlaggning A - Reaktor 1",
    object: "R1-SC-04",
    requestedStart: "2026-03-05",
    duration: "16 timmar",
    riskImpact: "Hog - Reaktordelsystem ur drift under arbetet. Kravs samordning med driftcentral.",
    status: "needs_more_info",
    priority: "critical",
    createdBy: "Per Nilsson",
    createdByRole: "applicant",
    createdAt: "2026-02-05T14:00:00",
    updatedAt: "2026-02-15T09:30:00",
    assignedTo: "Maria Svensson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: false, note: "Nytt schema kravs efter PLC-andring" },
      { id: "r3", label: "Reservdelar bestallda", fulfilled: false, note: "PLC-modul ej levererad" },
      { id: "r4", label: "Sakerhetsgenomgang genomford", fulfilled: false, note: "Vanter pa uppdaterad riskanalys" },
      { id: "r5", label: "Berorda system identifierade", fulfilled: true },
      { id: "r6", label: "Samordning med driftcentral", fulfilled: false },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-05T14:00:00", actor: "Per Nilsson", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-05T15:00:00", actor: "Per Nilsson", role: "applicant", action: "Skickade in for granskning" },
      { id: "a3", timestamp: "2026-02-07T08:30:00", actor: "Maria Svensson", role: "shiftlead2", action: "Tilldelade sig arendet" },
      { id: "a4", timestamp: "2026-02-15T09:30:00", actor: "Maria Svensson", role: "shiftlead2", action: "Begarde komplettering", comment: "Vg bifoga uppdaterat arbetsschema for PLC-byte samt bekrafta leveransdatum for PLC-modul." },
    ],
    attachments: [
      { id: "att1", name: "Riskanalys_R1SC04.pdf", type: "pdf", size: "3.2 MB", uploadedBy: "Per Nilsson", uploadedAt: "2026-02-05T14:15:00", version: 1 },
      { id: "att2", name: "PLC_Specifikation.pdf", type: "pdf", size: "5.6 MB", uploadedBy: "Per Nilsson", uploadedAt: "2026-02-05T14:20:00", version: 1 },
    ],
    documents: [
      { id: "doc1", name: "ARB.BEG #1003", version: 1, generatedBy: "System", generatedAt: "2026-02-05T15:00:00", format: "pdf" },
    ],
    approvers: [
      { role: "shiftlead1", name: "Erik Johansson" },
      { role: "shiftlead2", name: "Maria Svensson" },
    ],
  },
  {
    id: "ARB-1004",
    title: "Kalibrering av tryckmatare PM-201",
    description: "Rutinkalibrering av tryckmatare PM-201 i elforsorjningssystemet.",
    facility: "Anlaggning D - Elforsorjning",
    object: "PM-201",
    requestedStart: "2026-02-18",
    duration: "2 timmar",
    riskImpact: "Lag - Ingen driftpaverkan, redundant matare tillganglig.",
    status: "planned",
    priority: "low",
    createdBy: "Anna Lindqvist",
    createdByRole: "applicant",
    createdAt: "2026-02-01T10:00:00",
    updatedAt: "2026-02-16T08:00:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
      { id: "r3", label: "Reservdelar bestallda", fulfilled: true },
      { id: "r4", label: "Sakerhetsgenomgang genomford", fulfilled: true },
      { id: "r5", label: "Berorda system identifierade", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-01T10:00:00", actor: "Anna Lindqvist", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-01T10:30:00", actor: "Anna Lindqvist", role: "applicant", action: "Skickade in for granskning" },
      { id: "a3", timestamp: "2026-02-03T09:00:00", actor: "Erik Johansson", role: "shiftlead1", action: "Godkande" },
      { id: "a4", timestamp: "2026-02-05T11:00:00", actor: "Maria Svensson", role: "shiftlead2", action: "Godkande" },
      { id: "a5", timestamp: "2026-02-16T08:00:00", actor: "Erik Johansson", role: "shiftlead1", action: "Planerade till 2026-02-18 kl 10:00" },
    ],
    attachments: [],
    documents: [
      { id: "doc1", name: "ARB.BEG #1004", version: 1, generatedBy: "System", generatedAt: "2026-02-01T10:30:00", format: "pdf" },
    ],
    approvers: [
      { role: "shiftlead1", name: "Erik Johansson", approved: true, date: "2026-02-03" },
      { role: "shiftlead2", name: "Maria Svensson", approved: true, date: "2026-02-05" },
    ],
  },
  {
    id: "ARB-1005",
    title: "Reparation av larmkabel sektion 7",
    description: "Larmkabel i sektion 7 uppvisar intermittent fel. Behover lokaliseras och bytas.",
    facility: "Anlaggning A - Reaktor 1",
    object: "LK-S7",
    requestedStart: "2026-02-22",
    duration: "6 timmar",
    riskImpact: "Medel - Larmfunktion nedsatt i sektionen under arbetet.",
    status: "submitted",
    priority: "high",
    createdBy: "Per Nilsson",
    createdByRole: "applicant",
    createdAt: "2026-02-15T07:00:00",
    updatedAt: "2026-02-15T07:00:00",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: false },
      { id: "r3", label: "Reservdelar bestallda", fulfilled: true },
      { id: "r4", label: "Sakerhetsgenomgang genomford", fulfilled: false },
      { id: "r5", label: "Berorda system identifierade", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-15T07:00:00", actor: "Per Nilsson", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [
      { id: "att1", name: "Felrapport_LKS7.pdf", type: "pdf", size: "0.8 MB", uploadedBy: "Per Nilsson", uploadedAt: "2026-02-15T07:05:00", version: 1 },
    ],
    documents: [
      { id: "doc1", name: "ARB.BEG #1005", version: 1, generatedBy: "System", generatedAt: "2026-02-15T07:00:00", format: "pdf" },
    ],
    approvers: [
      { role: "shiftlead1", name: "Erik Johansson" },
      { role: "shiftlead2", name: "Maria Svensson" },
    ],
  },
  {
    id: "ARB-1007",
    title: "Arbetsorder 1",
    description: "Arbetsorder 1 beskrivning.",
    facility: "Anlaggning A - Reaktor 1",
    object: "AO-001",
    requestedStart: "2026-02-20",
    duration: "4 timmar",
    riskImpact: "Lag - Ingen driftpaverkan.",
    status: "submitted",
    priority: "medium",
    createdBy: "Anna Lindqvist",
    createdByRole: "applicant",
    createdAt: "2026-02-17T08:00:00",
    updatedAt: "2026-02-17T08:00:00",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: false },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: false },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-17T08:00:00", actor: "Anna Lindqvist", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1008",
    title: "Arbetsorder 2",
    description: "Arbetsorder 2 beskrivning.",
    facility: "Anlaggning B - Turbin 2",
    object: "AO-002",
    requestedStart: "2026-02-21",
    duration: "3 timmar",
    riskImpact: "Lag - Ingen driftpaverkan.",
    status: "submitted",
    priority: "low",
    createdBy: "Karin Bergstrom",
    createdByRole: "applicant",
    createdAt: "2026-02-17T09:00:00",
    updatedAt: "2026-02-17T09:00:00",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: false },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: false },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-17T09:00:00", actor: "Karin Bergstrom", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1009",
    title: "Arbetsorder 3",
    description: "Arbetsorder 3 beskrivning.",
    facility: "Anlaggning C - Kylsystem",
    object: "AO-003",
    requestedStart: "2026-02-22",
    duration: "2 timmar",
    riskImpact: "Lag - Ingen driftpaverkan.",
    status: "submitted",
    priority: "high",
    createdBy: "Per Nilsson",
    createdByRole: "applicant",
    createdAt: "2026-02-17T10:00:00",
    updatedAt: "2026-02-17T10:00:00",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: false },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: false },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-17T10:00:00", actor: "Per Nilsson", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1010",
    title: "Skriven driftorder 1",
    description: "Skriven driftorder 1 beskrivning.",
    facility: "Anlaggning A - Reaktor 1",
    object: "SD-001",
    requestedStart: "2026-02-23",
    duration: "5 timmar",
    riskImpact: "Lag - Ingen driftpaverkan.",
    status: "review",
    priority: "medium",
    createdBy: "Anna Lindqvist",
    createdByRole: "applicant",
    createdAt: "2026-02-18T08:00:00",
    updatedAt: "2026-02-18T08:00:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-18T08:00:00", actor: "Anna Lindqvist", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1011",
    title: "Skriven driftorder 2",
    description: "Skriven driftorder 2 beskrivning.",
    facility: "Anlaggning B - Turbin 2",
    object: "SD-002",
    requestedStart: "2026-02-24",
    duration: "4 timmar",
    riskImpact: "Lag - Ingen driftpaverkan.",
    status: "review",
    priority: "low",
    createdBy: "Karin Bergstrom",
    createdByRole: "applicant",
    createdAt: "2026-02-18T09:00:00",
    updatedAt: "2026-02-18T09:00:00",
    assignedTo: "Maria Svensson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-18T09:00:00", actor: "Karin Bergstrom", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1012",
    title: "Skriven driftorder 3",
    description: "Skriven driftorder 3 beskrivning.",
    facility: "Anlaggning C - Kylsystem",
    object: "SD-003",
    requestedStart: "2026-02-25",
    duration: "3 timmar",
    riskImpact: "Lag - Ingen driftpaverkan.",
    status: "review",
    priority: "high",
    createdBy: "Per Nilsson",
    createdByRole: "applicant",
    createdAt: "2026-02-18T10:00:00",
    updatedAt: "2026-02-18T10:00:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-18T10:00:00", actor: "Per Nilsson", role: "applicant", action: "Skapade och skickade in arbetsbegaran" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1013",
    title: "Driftorder under utförande 1",
    description: "Driftorder under utförande 1 beskrivning.",
    facility: "Anlaggning D - Elforsorjning",
    object: "DU-001",
    requestedStart: "2026-02-19",
    duration: "6 timmar",
    riskImpact: "Medel - Arbete pagår.",
    status: "planned",
    priority: "medium",
    createdBy: "Anna Lindqvist",
    createdByRole: "applicant",
    createdAt: "2026-02-15T08:00:00",
    updatedAt: "2026-02-19T08:00:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
      { id: "r3", label: "Sakerhetsgenomgang genomford", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-15T08:00:00", actor: "Anna Lindqvist", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-19T08:00:00", actor: "Erik Johansson", role: "shiftlead1", action: "Startade arbetet" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1014",
    title: "Driftorder under utförande 2",
    description: "Driftorder under utförande 2 beskrivning.",
    facility: "Anlaggning A - Reaktor 1",
    object: "DU-002",
    requestedStart: "2026-02-19",
    duration: "8 timmar",
    riskImpact: "Medel - Arbete pagår.",
    status: "planned",
    priority: "high",
    createdBy: "Karin Bergstrom",
    createdByRole: "applicant",
    createdAt: "2026-02-14T09:00:00",
    updatedAt: "2026-02-19T09:00:00",
    assignedTo: "Maria Svensson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
      { id: "r3", label: "Sakerhetsgenomgang genomford", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-14T09:00:00", actor: "Karin Bergstrom", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-19T09:00:00", actor: "Maria Svensson", role: "shiftlead2", action: "Startade arbetet" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1015",
    title: "Driftorder under utförande 3",
    description: "Driftorder under utförande 3 beskrivning.",
    facility: "Anlaggning B - Turbin 2",
    object: "DU-003",
    requestedStart: "2026-02-18",
    duration: "4 timmar",
    riskImpact: "Lag - Arbete pagår.",
    status: "planned",
    priority: "low",
    createdBy: "Per Nilsson",
    createdByRole: "applicant",
    createdAt: "2026-02-13T10:00:00",
    updatedAt: "2026-02-18T10:00:00",
    assignedTo: "Erik Johansson",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: true },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: true },
      { id: "r3", label: "Sakerhetsgenomgang genomford", fulfilled: true },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-13T10:00:00", actor: "Per Nilsson", role: "applicant", action: "Skapade arbetsbegaran" },
      { id: "a2", timestamp: "2026-02-18T10:00:00", actor: "Erik Johansson", role: "shiftlead1", action: "Startade arbetet" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
  {
    id: "ARB-1006",
    title: "Byte av filter i ventilationssystem",
    description: "Planerat filterbyte i ventilationssystem VS-3. Standardunderhall.",
    facility: "Anlaggning B - Turbin 2",
    object: "VS-3",
    requestedStart: "2026-02-28",
    duration: "3 timmar",
    riskImpact: "Lag - Ventilationskapacitet temporart reducerad.",
    status: "draft",
    priority: "low",
    createdBy: "Karin Bergstrom",
    createdByRole: "applicant",
    createdAt: "2026-02-16T06:00:00",
    updatedAt: "2026-02-16T06:00:00",
    requisites: [
      { id: "r1", label: "Riskanalys bifogad", fulfilled: false },
      { id: "r2", label: "Arbetsschema godkant", fulfilled: false },
      { id: "r3", label: "Reservdelar bestallda", fulfilled: true },
      { id: "r4", label: "Sakerhetsgenomgang genomford", fulfilled: false },
      { id: "r5", label: "Berorda system identifierade", fulfilled: false },
    ],
    activityLog: [
      { id: "a1", timestamp: "2026-02-16T06:00:00", actor: "Karin Bergstrom", role: "applicant", action: "Skapade utkast" },
    ],
    attachments: [],
    documents: [],
    approvers: [],
  },
]
